/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.validation;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MGPLValidator extends AbstractMGPLValidator {
	public static final String DUPLICATE_ATTRIBUTE = "duplicateAttribute";
	public static final String MANDATORY_ATTRIBUTE_MISSING = "mandatoryAttributeMissing";
	public static final String ONLY_CONSTANTS = "onlyConstants";
	public static final String ILLEGAL_VALUE = "illegalValue";
	public static final String ILLEGAL_ATTRIBUTE_NAME = "illegalAttributeName";
	public static final String DUPLICATE_DECLARATION = "duplicateDeclaration";
	public static final String NO_MATCHING_DECLARATION = "noMatchingDeclaration";
	public static final String NO_MATCHING_ANIM_BLOCK = "noMatchingAnimationBlock";
	public static final String INVALID_PROPERTY_ACCESS = "invalidPropertyAccess";
	public static final String NO_MATCHING_PROPERTY = "noMatchingProperty";
}
