/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anim Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AnimBlock#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AnimBlock#getObjType <em>Obj Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AnimBlock#getObjName <em>Obj Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAnimBlock()
 * @model
 * @generated
 */
public interface AnimBlock extends Block
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAnimBlock_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.AnimBlock#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Obj Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj Type</em>' attribute.
   * @see #setObjType(String)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAnimBlock_ObjType()
   * @model
   * @generated
   */
  String getObjType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.AnimBlock#getObjType <em>Obj Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj Type</em>' attribute.
   * @see #getObjType()
   * @generated
   */
  void setObjType(String value);

  /**
   * Returns the value of the '<em><b>Obj Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj Name</em>' attribute.
   * @see #setObjName(String)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAnimBlock_ObjName()
   * @model
   * @generated
   */
  String getObjName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.AnimBlock#getObjName <em>Obj Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj Name</em>' attribute.
   * @see #getObjName()
   * @generated
   */
  void setObjName(String value);

} // AnimBlock
