/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ass Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AssStmt#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AssStmt#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAssStmt()
 * @model
 * @generated
 */
public interface AssStmt extends Stmt
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Var)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAssStmt_Var()
   * @model containment="true"
   * @generated
   */
  Var getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.AssStmt#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Var value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(Expression)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAssStmt_Assignment()
   * @model containment="true"
   * @generated
   */
  Expression getAssignment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.AssStmt#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(Expression value);

} // AssStmt
