/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attr Ass List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mGPL.AttrAssList#getAttrAss <em>Attr Ass</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAttrAssList()
 * @model
 * @generated
 */
public interface AttrAssList extends EObject
{
  /**
   * Returns the value of the '<em><b>Attr Ass</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mGPL.AttrAss}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr Ass</em>' containment reference list.
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getAttrAssList_AttrAss()
   * @model containment="true"
   * @generated
   */
  EList<AttrAss> getAttrAss();

} // AttrAssList
