/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getIfStmt()
 * @model
 * @generated
 */
public interface IfStmt extends Stmt
{
} // IfStmt
