/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getStmt()
 * @model
 * @generated
 */
public interface Stmt extends EObject
{
} // Stmt
