/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mGPL.Var#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mGPL.Var#getVarArray <em>Var Array</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mGPL.Var#getVarProp <em>Var Prop</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVar_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.Var#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var Array</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Array</em>' containment reference.
   * @see #setVarArray(VarArray)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVar_VarArray()
   * @model containment="true"
   * @generated
   */
  VarArray getVarArray();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.Var#getVarArray <em>Var Array</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Array</em>' containment reference.
   * @see #getVarArray()
   * @generated
   */
  void setVarArray(VarArray value);

  /**
   * Returns the value of the '<em><b>Var Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Prop</em>' containment reference.
   * @see #setVarProp(VarProp)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVar_VarProp()
   * @model containment="true"
   * @generated
   */
  VarProp getVarProp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.Var#getVarProp <em>Var Prop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Prop</em>' containment reference.
   * @see #getVarProp()
   * @generated
   */
  void setVarProp(VarProp value);

} // Var
