/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mGPL.VarDecl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVarDecl()
 * @model
 * @generated
 */
public interface VarDecl extends Decl
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Init)
   * @see org.xtext.example.mydsl.mGPL.MGPLPackage#getVarDecl_Value()
   * @model containment="true"
   * @generated
   */
  Init getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mGPL.VarDecl#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Init value);

} // VarDecl
