/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mgpl.ui.internal.MgplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MGPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MgplActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MgplActivator activator = MgplActivator.getInstance();
		return activator != null ? activator.getInjector(MgplActivator.ORG_XTEXT_EXAMPLE_MYDSL_MGPL) : null;
	}

}
