/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mgpl.ui.internal.MgplActivator;

public class MGPLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MgplActivator.getInstance().getInjector("org.xtext.example.mydsl.MGPL");
	}

}
