/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MGPLRuntimeModule;
import org.xtext.example.mydsl.MGPLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MGPLIdeSetup extends MGPLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MGPLRuntimeModule(), new MGPLIdeModule()));
	}
	
}
