/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.mGPL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.mGPL.IfStmt;
import org.xtext.example.mydsl.mGPL.MGPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>If Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IfStmtImpl extends StmtImpl implements IfStmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IfStmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MGPLPackage.Literals.IF_STMT;
  }

} //IfStmtImpl
